name: Deploy book
on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday 6 AM UTC

permissions: {}

jobs:
  build:
    name: Build book
    outputs:
      branch: ${{ steps.branch.outputs.branch }}
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Extract branch name to deploy
        id: branch
        shell: bash -x {0}
        run: |
          if [[ ${GITHUB_BASE_REF:-$GITHUB_REF} =~ ^(refs/heads/)?(master|release/[0-9][0-9.]+)$ ]]; then
            echo "branch=${BASH_REMATCH[2]#release/}" >> "${GITHUB_OUTPUT}"
          fi
      - name: Install Crystal
        id: crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ steps.branch.outputs.branch }}
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt') }}
          restore-keys: pip-
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Determine a version for API doc links
        shell: bash -x {0}
        run: |
          if [[ "${STEPS_BRANCH_OUTPUTS_BRANCH}" =~ ^[0-9] ]]; then
            echo "CRYSTAL_VERSION=${STEPS_CRYSTAL_OUTPUTS_CRYSTAL}" >> "${GITHUB_ENV}"
          fi
        env:
          STEPS_BRANCH_OUTPUTS_BRANCH: ${{ steps.branch.outputs.branch }}
          STEPS_CRYSTAL_OUTPUTS_CRYSTAL: ${{ steps.crystal.outputs.crystal }}
      - name: Populate sample version of Crystal
        run: crystal --version | tee crystal-version.txt
      - name: Set edit_uri branch
        run: |
          sed -i -e "s#^edit_uri:.*#edit_uri: https://github.com/${GITHUB_REPOSITORY}/edit/${GITHUB_REF_NAME}/docs/#" mkdocs.yml
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
      - name: Build book
        run: LINT=true make build
      - name: Upload site
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site/
          if-no-files-found: error

  deploy:
    name: Deploy book
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && needs.build.outputs.branch != '' && github.repository == 'crystal-lang/crystal-book'
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: site/
      - name: Deploy book
        run: aws s3 sync ./site "s3://crystal-book/reference/${STEPS_BRANCH_OUTPUTS_BRANCH}" --delete
        env:
          STEPS_BRANCH_OUTPUTS_BRANCH: ${{ steps.branch.outputs.branch }}

